spring:
  application:
    name: ExperimentsInJavaTemplate
  data:
    redis:
      client-type: jedis
      sentinel:
        master: mymaster
        nodes:
          - localhost:26379
          - localhost:26380
        username: username
        password: password
      # password: yourpassword
      # database: 0
